<?php

namespace tests\codility\maximum_slice_problem;

use codility\maximum_slice_problem\MaxProfit;
use PHPUnit\Framework\TestCase;
use tests\utils\TestsAcceptance;

class MaxProfitTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExample()
    {
        // TODO use TestsAcceptance to build more cases

        $maxProfit = new MaxProfit();

        $this->assertEquals( $maxProfit->solution([6]), 0);
    }
}